version: '3'
services:
  jenkins:
    user: root
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    restart: always
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - 8080:8080
      - 5000:5000
    volumes:
      - vol:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  vol:
