version: '3'
services:
  ui:
    image: portainer/portainer:linux-arm-1.19.1
    restart: unless-stopped
    ports:
      - 9000:9000
    #expose:
    #  - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data:
