version: '3'
services:
  redis:
    image: redis:4.0.11-alpine3.8
    ports:
    - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
