version: "3.0"
services:
  pi-hole:
    image: pihole/pihole:v4.0_amd64
    # No es necesario
    #container_name: pi-hole
    restart: unless-stopped
    ports:
     - "53:53/tcp"    #DNS
     - "53:53/udp"    #DNS
     - "80:80/tcp"    #HTTP
     - "443:443/tcp"  #SSL
    # - "67:67/udp" #DHCP
    # Por si se quieren poner las env variables en un archivo .env
    #env_file:
    #  - .env
    environment:
      ServerIP: ${IP:?err}
      WEBPASSWORD: pi123
      TZ: America/Bogota
    volumes:
      # Usando bind mount
      #- ./pi-hole-volumes/pihole:/etc/pihole/
      #- ./pi-hole-volumes/dnsmasq.d:/etc/dnsmasq.d/
      # Usando named volumes
      - etc_pi-hole:/etc/pihole
      - etc_dnsmasq.d:/etc/dnsmasq.d
volumes:
  etc_pi-hole:
  etc_dnsmasq.d:
