version: '3'
services:
  pi-hole:
    image: diginc/pi-hole:debian_v3.3
    # No es necesario
    #container_name: pi-hole
    restart: unless-stopped
    ports:
     - 53:53/tcp
     - 53:53/udp
     - 80:80
    # Por si se quieren poner las env variables en un archivo .env
    #env_file:
    #  - .env
    environment:
      ServerIP: $IP
      WEBPASSWORD: pi123
      TZ: America/Bogota
    volumes:
      # Aunque la carpeta pi-hole-volumes esta ignorada por git, es persistente
      # cuando se hace git pull
      #- ./pi-hole-volumes/pihole:/etc/pihole/
      #- ./pi-hole-volumes/dnsmasq.d:/etc/dnsmasq.d/
      # Usando named volumes
      - etc_pi-hole:/etc/pihole
      - etc_dnsmasq.d:/etc/dnsmasq.d
volumes:
  etc_pi-hole:
  etc_dnsmasq.d:
